version: '3.3'

volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: drag0nsigh/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/collected_static
      - media:/app/media
      - docs:/app/docs
    depends_on:
      - db

  frontend:
    image: drag0nsigh/foodgram_frontend
    volumes:
      - frontend_static:/app/build/

  nginx:
    container_name: foodgram-proxy
    image: drag0nsigh/foodgram_gateway
    ports:
      - "8090:80"
    volumes:
      - backend_static:/static
      - frontend_static:/frontend_static
      - media:/media
      - docs:/static/docs/