version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/app/docs
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    volumes:
      - static:/app/build/static/

  nginx:
    container_name: foodgram-proxy
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
      - docs:/static/docs/
    depends_on:
      - backend