import os

from dotenv import load_dotenv

load_dotenv()

MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERS_CHAR = 150

MAX_LENGTH_INGREDIENTS_NAME = 128
MAX_LENGTH_INGREDIENTS_UNIT = 64
MAX_LENGTH_TAG_CHAR = 32

MIN_COOKING_TIME = 1
MAX_LENGTH_RECIPE_NAME = 128

MIN_AMOUNT = 1

PATTERN_VALID_USERNAME = r'^[\w.@+-]+\Z'
URL_PATH_ME = 'me'

MAIN_URL = os.getenv('MAIN_URL')
